### ISSUE TITLE
[M0-Dev] Definición de la clase Alumno

### ISSUE THREAD

**Issue by LuisMart7** [danielsp13/SuperCatch#15]
Según la [HU03](https://github.com/danielsp13/SuperCatch/blob/main/docs/user-stories.md#black_nib-hu03-irene-necesita-entrenar-para-sus-ex%C3%A1menes), el alumno puede ir practicando haciendo distintas pruebas por lo que no sé como filtrar las respuestas que son de prueba con las respuestas que luego si irán asociadas al examen real.

**Comment by LuisMart7** [comment]
@danielsp13 nuevamente asigna M0. Gracias.

**Comment by LuisMart7** [comment]
Lo que podría hacerse es otra clase _pruebasAlumno_ donde se recoja cada prueba realizada previamente por el alumno para que vaya contemplando el avance y se pueda aplicar el algoritmo igualmente. Además, no se mezclaría la evaluación real de las respuestas (incluida en la clase resolucionExamen) con las pruebas que haga el alumno en su casa. Dime cuál es tu opinión.

**Comment by LuisMart7** [comment]
Por lo tanto, tendríamos un objeto valor en la clase Alumno y esta sería la entidad que va modificándose cada vez que el alumno va realizando cada prueba.

**Comment by LuisMart7** [comment]
Aunque si es cierto que si vamos añadiendo las calificaciones de cada examen al perfil del alumno, sería una entidad pues va modificándose. No sé cómo lo quieres enfocar, tú me dices.

**Comment by danielsp13** [comment]
> Lo que podría hacerse es otra clase _pruebasAlumno_ donde se recoja cada prueba realizada previamente por el alumno para que vaya contemplando el avance y se pueda aplicar el algoritmo igualmente. Además, no se mezclaría la evaluación real de las respuestas (incluida en la clase resolucionExamen) con las pruebas que haga el alumno en su casa. Dime cuál es tu opinión.

¿Qué tendría de diferente con respecto a la clase *resolucionExamen*?

**Comment by danielsp13** [comment]
> Aunque si es cierto que si vamos añadiendo las calificaciones de cada examen al perfil del alumno, sería una entidad pues va modificándose. No sé cómo lo quieres enfocar, tú me dices.

Me parece que estás en lo correcto. Debería ser un objeto valor como antes has comentado, ya que realmente, sólo usaríamos esa clase para definir al alumno, y almacenar más datos que en este caso sería la calificación de pruebas, exámenes reales... Es una cuestión en la que tengo el mismo dilema que tú pero me parece más acertado lo primero que has dicho.

**Comment by LuisMart7** [comment]
Sería una cuestión de si la clase Alumno va a ser un objeto valor, vamos a necesitar otra clase donde podamos ir añadiendo las calificaciones que cada alumno vaya teniendo. Por lo tanto, creo que lo mejor sería:
Objetos valor: Pregunta (respuesta correcta) y Respuesta (respuesta del alumno en prueba/examen con calificación de la misma)
Entidades: ResolucionExamen (tendremos el id del examen, las preguntas asociadas identificadas por el numero de la pregunta y las respuestas del todos los alumnos en el examen filtradas por dni del alumno y numero de la pregunta (así pueden estar desordenadas)) y Alumno (donde además de los datos inmutables de la persona, iríamos añadiendo las calificaciones que obtiene para cada examen)
Lo único que fallaría sería el seguimiento de la evolución según las pruebas que va haciendo cada alumno para ver si mejora (deberíamos tener un registro) según la [HU03](https://github.com/danielsp13/SuperCatch/blob/main/docs/user-stories.md#black_nib-hu03-irene-necesita-entrenar-para-sus-ex%C3%A1menes). Eso es lo único que me falta para cerrar la implementación. Si no hiciera falta un registro, creo que estaría todo para subirlo y que lo revisaras.

**Comment by danielsp13** [comment]
Dejame que lo piense un momento. Mientras tanto, con respecto a lo que te he preguntado antes. ¿Qué has decidido sobre la clase *pruebasAlumno*?

**Comment by danielsp13** [comment]
@LuisMart7 . Me gustaría ver la implementación que tienes actualmente. No te preocupes si luego hay que modificar algo o no se ajusta a lo que hemos estado hablando. Yo te lo notifico.

Ten cuidado con los commits. Súbelo todo poco a poco. E identifícalo todo bien todo lo que has hecho tanto en el subject como en la descripción.

**Comment by danielsp13** [comment]
Con eso podré ver mejor si podemos dejarlo así o no vaya. Si hay algo que ya hayas subido a la rama y no te haya dado feedback. Mencioname en el PR

**Comment by LuisMart7** [comment]
La clase pruebasAlumno la veo innecesario. Porque con la clase resolucionExamen se puede individualizar un examen que se haga de prueba y entonces no es necesaria. Únicamente definiría las clases que he mencionado previamente. ¿Qué opinas @danielsp13 ?

**Comment by LuisMart7** [comment]
En cuanto  a la implementación he avanzado en las clases Pregunta y Respuesta pero hasta saber como implementar las clases resolucionExamen y Alumno no sé qué subir. 
En lo relativo a la clase Alumno, ¿quieres objeto valor o entidad (se van añadiendo las calificaciones de cada examen)? Si no se quiere tener registro de los exámenes pasados creo que podría ser objeto valor con la calificación que tenga en el examen y punto. Por lo tanto, podemos añadir la calificación como una única relativa al examen que se haga y no un registro de las anteriores.

**Comment by LuisMart7** [comment]
Lo único que veo raro es definir una única calificación en el objeto valor Alumno porque no representa un campo real del propio Alumno. Se podría añadir una lista de calificaciones que sean pares <id_alumno, calificación_total> en la clase resolucionExamen. Tú dime las opiniones. Voy a subir lo que tengo al pull request y le echas un ojo.

**Comment by LuisMart7** [comment]
@danielsp13 creo que la última duda que tengo es si poner las calificaciones resultantes del examen en la clase Alumno como un registro o poner una lista de notas en la clase ResolucionExamen que ordenes las notas de cada alumno del examen que se realice. Te menciono en el pull request.

**Comment by LuisMart7** [comment]
@danielsp13 he subido un borrador. Todavía sigo modificando cosas.
Creo que la mejor manera de hacerlo es que alumno sea un objeto valor y añadir un campo en la clase resolucionExamen que sea la lista de calificaciones filtradas por el id del alumno.
Además, he añadido a la clase Respuesta el id del alumno que la hace para que puedas sacar quién la ha realizado en la clase  resolucionExamen. Cuando tenga tiempo subo las modificaciones y el borrador definitivo que creo que es lo mejor.
En el README.md te explicaré todo como lo he pensado.

**Comment by danielsp13** [comment]
> @danielsp13 he subido un borrador. Todavía sigo modificando cosas. Creo que la mejor manera de hacerlo es que alumno sea un objeto valor y añadir un campo en la clase resolucionExamen que sea la lista de calificaciones filtradas por el id del alumno. Además, he añadido a la clase Respuesta el id del alumno que la hace para que puedas sacar quién la ha realizado en la clase resolucionExamen. Cuando tenga tiempo subo las modificaciones y el borrador definitivo que creo que es lo mejor. En el README.md te explicaré todo como lo he pensado.

Recibido. Por favor, coloca este comentario al PR en vez de en este issue que aqui no tiene mucho que ver. Te mandaré feedback lo antes que pueda.
