### ISSUE TITLE
[M0-Dev] Definición de la clase Respuesta

### ISSUE THREAD

**Issue by LuisMart7** [danielsp13/SuperCatch#16]
Según lo dispuesto en https://github.com/danielsp13/SuperCatch/issues/5 acorde a la HU01, la agilización de la corrección podría verse satisfecha mediante dos manera:
1) Definir un campo de tipo entero "numero" que identifica el número de la pregunta a la que se responde con la Respuesta por lo que posteriormente se habría de comparar ambos números (tanto de pregunta como de respuesta) para saber a qué pregunta se está respondiendo.
2) Definir en la clase Respuesta, un campo del tipo Pregunta que es la pregunta a la que se responde.
¿Qué definición ves mejor para la clase Respuesta?
@danielsp13 asocia M0 por favor.

**Comment by danielsp13** [comment]
Aquí necesito que me comentes cuál es el problema, la solución, la tengo que ver en el código que implementes...

**Comment by LuisMart7** [comment]
De acuerdo. Mi problema es a la hora de asociar la Respuesta que realice el alumno con la Pregunta que corresponda. No sé si con un entero que defina el número de la pregunta, con un instancia de la clase Pregunta,...

**Comment by danielsp13** [comment]
> De acuerdo. Mi problema es a la hora de asociar la Respuesta que realice el alumno con la Pregunta que corresponda. No sé si con un entero que defina el número de la pregunta, con un instancia de la clase Pregunta,...

Ponlo en el cuerpo del issue mejor por favor.
