### ISSUE TITLE
No se especifica cuánto es un texto considerable

### ISSUE THREAD

**Issue by LuisMart7** [danielsp13/SuperCatch#22]
No queda claro que longitud tiene que tener el texto de la respuesta de acuerdo a la HU01 #5.

**Comment by LuisMart7** [comment]
La mejor opción que veo es que sea texto considerable todo tipo de respuesta que supere más de 50 palabras con el fin de que el alumno no opte por poner palabras sueltas sino un texto organizado y coherente.

**Comment by danielsp13** [comment]
Lo había asignado al Milestone 0, pero he visto que este *issue* es una cuestión que no tiene que ver específicamente con el modelo, si no en vistas de la lógica que implemente (entiendo yo). ¿Es así?
