### ISSUE TITLE
[M0 - Dev] Ausencia de clases y módulos para desarrollo de lógica de negocio

### ISSUE THREAD

**Issue by danielsp13** [danielsp13/SuperCatch#32]
El problema es no haber resuelto #10 , desarrollando clases, módulos o entidades que realmente solucionen el problema que se presenta en #5 . 

En #31 , se deberá completar este trabajo antes de continuar con la lógica de negocio.

**Comment by JJ** [comment]
Si esto es un problema, la simple existencia de un módulo lo resolvería. Por lo tento, no está correctamente planteado.
