### ISSUE TITLE
[M2 - Dev] Problema en test de versión 3.12-rc

### ISSUE THREAD

**Issue by danielsp13** [danielsp13/SuperCatch#76]
Se produce un fallo a la hora de probar la versión `3.12-rc`, debido a que en esta nueva versión se produce un cambio en la forma de instalar paquetes que requieren compilación, como es lo que indica en:
* [setup.py removal](https://discuss.python.org/t/setup-py-removal-python-3-12/17335)
* [build C extensions without setup.py](https://github.com/python/cpython/pull/94474)

**Comment by JJ** [comment]
¿Esto es necesario para hacer test?
libffi se usa para hacer interfaz con aplicaciones binarias. gcc, evidentemente, para compilarlas.
Si ambas cosas son necesarias, lo son posiblemente para `nltk`, pero es muy improbable que haga falta para tus tests específicos.

**Comment by danielsp13** [comment]
> ¿Esto es necesario para hacer test? libffi se usa para hacer interfaz con aplicaciones binarias. gcc, evidentemente, para compilarlas. Si ambas cosas son necesarias, lo son posiblemente para `nltk`, pero es muy improbable que haga falta para tus tests específicos.

se lo he indicado en un comentario, es necesario para una dependencia muy concreta de poetry (se instale via pip o curl): `cffi`. Lo mejor será abordarlo en un issue que esté relacionado.
