### ISSUE TITLE
[M0-Dev] Elección del lenguaje de programación

### ISSUE THREAD

**Issue by LuisMart7** [danielsp13/SuperCatch#9]
Hola Daniel, soy Luis y he sido asignado para realizar tu milestone nº0. Lo primero que quería preguntarte es que lenguajes de programación te vienen mejor para hacerlo; por mí, Python o C++ son los que más domino pero puedo adaptarme. Aprovecho para preguntarte si el M1 debería de tener asignado una historia de usuario.

**Comment by danielsp13** [comment]
Buenas tardes luis, espero que pueda ayudarte en todo lo posible para superar el objetivo 2. :)

Cuando empecé a diseñar el proyecto  había considerado utilizar Python, ya que creo que el tratamiento vectorizado y el análisis del texto lo hace un candidato potencial para implementar el modelo y la posterior lógica de negocio. Como veo que es también con lo que estás más familiarizado, adelante, por mi perfecto.

Con respecto a lo que me mencionas sobre el milestone M1, en principio no lo había contemplado primero por el diseño propio de los hitos, pero agradezco tu pregunta, lo estudiaré y te daré mañana una respuesta para saber si es necesario que asocie una HU o deba hacer un cambio al respecto. Gracias por cometármelo.

Si necesitas cualquier cosa, aquí estoy.

**Comment by danielsp13** [comment]
Bueno, te respondo ahora para que no te quedes con la duda por si te vas a poner a trabajar en seguida.
Verás, mi idea cuando empecé a diseñar las fases del desarrollo, fue primero la representación del modelo en sí (Milestone [M0](https://github.com/danielsp13/SuperCatch/milestone/1), en la que hay que tener en cuenta las Historias de Usuario de Dolores #5,  y la de Irene #7, con las que creo que se identifican adecuadamente qué tipo de clases y entidades se necesitan.

Por esta cuestión, es por lo que no consideré asignar una Historia de Usuario en el milestone [M1](https://github.com/danielsp13/SuperCatch/milestone/1), ya que debe de haberse alcanzado un pvm suficiente para lo que dice el propósito de "agilizar la corrección de exámenes", en el sentido de que pasaríamos a tener un formato digital de los mismos en los que, como mínimo, el profesor pudiera verse satisfecho en ese aspecto aún sin lógica de negocio, y por la otra historia, "necesidad de entrenar".

No obstante, como se ha especificado en la HU1 que el deseo es "automatizar", propiamente es una clara referencia al hito 1, pero no sé si es correcto asignar el mismo HU a dos milestones.

**Comment by danielsp13** [comment]
PD: Ya que estás a cargo de mi proyecto, acepto sugerencias, así que cualquier otra duda que tengas o algo que consideres que sea importante, dímelo sin ningún tipo de problema.

PD2: Con ese avatar lo mínimo que te mereces es matrícula jajaja :100:

**Comment by LuisMart7** [comment]
Me parece buena argumentación la relación de milestones e historias de usuario por lo que yo lo dejaba como lo tenías en un principio. Como te va bien Python, lo implementaré con este lenguaje. Yo creo que podemos cerrar este issue y te iré abriendo uno conforme vaya pensando las clases a declarar y la forma de organizarlas. Esta semana te iré entregando avances. Ánimo a ti también.
